[package]
name = "testing"
version = "1.0.0"
authors = []

[addresses]
pokemon = "_"

[dev-addresses]
pokemon = "0x9000"

[dependencies]
AptosFramework = {git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects"}

[dev-dependencies]
